# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
# For security reasons, it is fatal to not use header ip behind a reverse proxy, using the header ip when in standalone mode just crashes the server - which is way better:
ip-from-header: "_env:IP_FROM_HEADER:true"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
development: true
detailed-logging: true
should-log-all: true
# reload-templates: false
# mutable-static: false
# skip-combining: false

copyright: "copyright by Robert Klotzner"
#analytics: UA-YOURCODE
